title: Emerson Hemley
description: Personal academic website
baseurl: "/my-website"
url: "https://ehemley.github.io"

# GitHub Pages settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
